# Generated by Django 4.1.1 on 2022-09-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumuser",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
