# Generated by Django 4.1.1 on 2023-02-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="created_date",
            new_name="created_at",
        ),
    ]
